force-app/main/default/objects/Chat_Message__e/Chat_Message__e.object-meta.xml
<CustomObject>
    <label>Chat Message</label>
    <pluralLabel>Chat Message</pluralLabel>
</CustomObject>

force-app/main/default/objects/Chat_Message__e/fields/Sender__c.field-meta.xml
<CustomField>
    <fullName>Sender__c</fullName>
    <label>Sender</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chat_Message__e/fields/TimeStamp__c.field-meta.xml
<CustomField>
    <fullName>TimeStamp__c</fullName>
    <label>TimeStamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ChatPublisher.cls
public  class ChatPublisher {
    @AuraEnabled
    public static void sendMessage(String sender, String message){
        try {
            Chat_Message__e chatMe = new Chat_Message__e();
            chatMe.Sender__c = sender;
            chatMe.Message__c = message;
            chatMe.TimeStamp__c = System.now();

            EventBus.publish(chatMe);
            System.debug('Message sent: ' + chatMe);
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}